version: '3.7'

services:

  cdn.nginx:
    container_name: ${COMPOSE_PROJECT_NAME}.nginx
    image: nginx:1.19.0
    depends_on:
      - cdn.thumbor
    volumes:
      - $PWD/docker/nginx/:/etc/nginx/templates/
      - ${MEDIA_DIRECTORY:-cdn.media}:/cdn-media
    environment:
      VIRTUAL_HOST: ${APP_DOMAIN}
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: ${APP_DOMAIN}
    networks:
      - backend
      - proxy
    env_file:
      - $PWD/.env


  cdn.thumbor:
    image: minimalcompact/thumbor
    container_name: ${COMPOSE_PROJECT_NAME}.thumbor
    environment:
      - THUMBOR_NUM_PROCESSES=${THUMBOR_NUM_PROCESSES:-1}
      - ENGINE_THREADPOOL_SIZE=${ENGINE_THREADPOOL_SIZE:-0}
      - CORS_ALLOW_ORIGIN=*
      - AUTO_WEBP=True
      - RESULT_STORAGE=thumbor.result_storages.file_storage
      - RESULT_STORAGE_STORES_UNSAFE=True
      - STORAGE=thumbor.storages.no_storage
      - LOADER=thumbor.loaders.file_loader
      - FILE_LOADER_ROOT_PATH=/cdn-media
    volumes:
      - $PWD/data/thumbor:/data
      - ${MEDIA_DIRECTORY:-cdn.media}:/cdn-media:ro
    networks:
      - proxy
      - backend



volumes:
  cdn.media:
    driver: local
    driver_opts:
      type: none
      device: /media
      o: bind


networks:
  backend:
  proxy:
    external:
      name: nginx-proxy

